service: batch-log-to-amazones

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "arn:aws:logs:*:*:*"
    - Effect: "Allow"
      Action:
        - "es:ESHttpPost"
      Resource: "*"

plugins:
  - serverless-python-requirements
  - serverless-prune-plugin

package:
  exclude:
    - venv/**
    - Python
    - tests/**
    - __pycache__/**

custom:
  stage: "${opt:stage, self:provider.stage}"
  envs: "${file(env-${self:custom.stage}.yml)}"
  pythonRequirements:
    dockerizePip: true
  prune:
    automatic: true
    number: 10

functions:
  runner:
    handler: batch_log_to_amazones.lambda_handler
    name: "${self:custom.stage}-batch_applilog_log_to_amazones"
    environment: ${self:custom.envs}